<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Verzenden</name>
   <tag></tag>
   <elementGuidId>b74340c5-b852-41cf-9dab-2975cc37d65e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#surveySubmitBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='surveySubmitBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>edb17840-0c75-4054-b807-8add9a512f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1b45dae3-fbb2-4edb-beb2-f4ba3e26239c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-submit pull-right </value>
      <webElementGuid>b100ffd7-f5e2-40be-a928-640c4a496280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>surveySubmitBtn</value>
      <webElementGuid>1710da3e-96c1-4b24-8d2e-b02aa97f898b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9f535f9e-6dc9-466b-a382-78db8c39b1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verzenden </value>
      <webElementGuid>a1c0d1db-5f47-4f02-8864-2b7bc151e8b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;surveySubmitBtn&quot;)</value>
      <webElementGuid>53be3c3c-0d35-48b4-95ab-e102b6382d15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='surveySubmitBtn']</value>
      <webElementGuid>b164aca9-94b4-4bb5-a716-646823af7ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page1']/div[4]/button</value>
      <webElementGuid>29ec32f7-71b0-4aba-abbc-de197a05eded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fijn om te horen! Kunt u kort vertellen waarom? Dit helpt ons om onze website te verbeteren.'])[1]/following::button[1]</value>
      <webElementGuid>5836033e-1a55-4178-93d7-13b1f6e4caad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dat is jammer. Kunt u kort vertellen waarom? Dit helpt ons om onze website te verbeteren.'])[1]/following::button[1]</value>
      <webElementGuid>480d7ab0-08e3-4d78-9fd1-008d8423497f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>67f8b96e-40ea-438b-aa5a-4fdd908eba41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'surveySubmitBtn' and @type = 'button' and (text() = 'Verzenden ' or . = 'Verzenden ')]</value>
      <webElementGuid>c2c01ced-7fb9-44c9-9fc7-aa585f11529f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
