<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ja</name>
   <tag></tag>
   <elementGuidId>17a9d1bb-b5c2-4d2a-993c-dd24b9fb6ab2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cookiemelding-doorgaan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='cookiemelding-doorgaan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>826daca7-0e80-4cc8-a6c6-5bd0dd0bbde1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cookiemelding-doorgaan</value>
      <webElementGuid>97b41323-61a7-4216-89ab-47ed21c554cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button--no-margin js-cookiebar__accept</value>
      <webElementGuid>dc0516b8-0696-4595-89f2-6531f3f0985a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3f0253d1-77ab-42b3-8f18-455cb09860f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ja</value>
      <webElementGuid>160c234a-5378-4999-a7b3-5cd90813e0de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cookiemelding-doorgaan&quot;)</value>
      <webElementGuid>6203403f-0c9e-431d-b849-cc3ce30ccf72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='cookiemelding-doorgaan']</value>
      <webElementGuid>e818f12a-5718-4019-913b-8f9d21b7ba44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cookiemelding']/div[2]/button</value>
      <webElementGuid>6334e085-5c31-4859-9398-c846b552169d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='privacy en cookies'])[1]/following::button[1]</value>
      <webElementGuid>1d10c39c-8585-4337-b4df-020c074fc3e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookies'])[1]/following::button[1]</value>
      <webElementGuid>75110fe5-d42d-46cf-ac44-fe34c38c1512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nee'])[1]/preceding::button[1]</value>
      <webElementGuid>b3afaa1c-96d4-4d19-9f7a-46497c050965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Direct naar content'])[1]/preceding::button[2]</value>
      <webElementGuid>e92e456a-7352-4761-bbb8-8112b6e48f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ja']/parent::*</value>
      <webElementGuid>538e1178-934e-421a-868f-1f973056dcd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>2c0e8612-1ed6-4c96-a0dc-7782b7a2f0bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'cookiemelding-doorgaan' and (text() = 'Ja' or . = 'Ja')]</value>
      <webElementGuid>5590a4f4-4872-408f-b0ca-c06e45951f65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
