<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bedankt voor uw feedback</name>
   <tag></tag>
   <elementGuidId>61f2bff7-ee78-4453-ad4b-05b6e036849e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#thanks-page_4enoyfamrilo8638538g5ut7jfzpynwh > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='thanks-page_4enoyfamrilo8638538g5ut7jfzpynwh']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e4dd7b2f-6ae8-4261-838f-20009aec6c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>85783377-926d-4757-8fd2-61b4fa4e3618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bedankt voor uw feedback!</value>
      <webElementGuid>1d94b9a0-3f89-4fe8-b86c-9752de7400b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;thanks-page_4enoyfamrilo8638538g5ut7jfzpynwh&quot;)/div[1]</value>
      <webElementGuid>991819db-257f-48f6-8119-bea5739fea31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='thanks-page_4enoyfamrilo8638538g5ut7jfzpynwh']/div</value>
      <webElementGuid>53435bf3-3474-464a-b6f5-3d6885d5e4cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekening betalen'])[2]/following::div[9]</value>
      <webElementGuid>473ff7b9-80fd-47cc-bfb6-b75100fa053d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bedankt voor uw feedback!']/parent::*</value>
      <webElementGuid>cab09b84-6ad6-499f-808e-1623c0dc2a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div</value>
      <webElementGuid>a23b2743-df42-419f-b093-cfd3510cbd4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Bedankt voor uw feedback!' or . = 'Bedankt voor uw feedback!')]</value>
      <webElementGuid>1d0f496b-faaf-4ba8-acef-e39def4771dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
