<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fijn om te horen Kunt u kort vertelle_933eda</name>
   <tag></tag>
   <elementGuidId>28b3ba12-12a9-4939-a315-205d68ba670e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#element-input-64796</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='element-input-64796']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a67684ad-a131-48fc-b101-996d4f75c4a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element-input-64796</value>
      <webElementGuid>529ddaa3-dfd5-413a-80e4-aaea8cbc3a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0e615c4f-038a-46a4-90bd-9f773a9c3a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>314a7a80-660c-47aa-9958-524b71befb49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element-input-64796&quot;)</value>
      <webElementGuid>4a8593ea-487d-4758-9da5-97cd15f24002</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element-input-64796']</value>
      <webElementGuid>910bbf74-f790-41be-bf4a-993725c8af43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='input-64796']/div/div/input</value>
      <webElementGuid>57b06a11-f35b-43c7-a43d-e0342bfb545a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>7fea1823-a0a4-45ed-9133-7c54d08f1d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'element-input-64796' and @type = 'text']</value>
      <webElementGuid>af9a6d14-cba4-43dc-9c73-6443094b65db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
