<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Ja</name>
   <tag></tag>
   <elementGuidId>0b012314-d203-4c08-8575-84c9ffbfb4d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.label_thumbs_positive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='thumbs-61017']/fieldset/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d9bd0ebb-ba00-40ae-ab2a-181bac5bc65f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>thumbs-61017_0</value>
      <webElementGuid>28f5552f-38ff-47d5-8a9b-6ab459fb4ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label_thumbs_positive</value>
      <webElementGuid>1b19ba78-5a57-4b00-9f02-462ecb399751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ja</value>
      <webElementGuid>fe1fd30e-9164-4cf4-aaf9-7b9f202cbdaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Ja</value>
      <webElementGuid>99f07cdc-7cb6-4b71-8b46-827579ea558d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;thumbs-61017&quot;)/fieldset[1]/div[@class=&quot;button-container thumbs-container&quot;]/div[@class=&quot;thumbs-wrapper button&quot;]/label[@class=&quot;label_thumbs_positive&quot;]</value>
      <webElementGuid>d0eac213-2eb4-496f-8ec8-028edc227c0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='thumbs-61017']/fieldset/div/div/label</value>
      <webElementGuid>f5f25951-4fb3-492e-af22-8229441c54a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vond u deze informatie nuttig?'])[1]/following::label[1]</value>
      <webElementGuid>9e0fb284-be6a-486b-a555-d1f77ebdb02c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekening betalen'])[2]/following::label[2]</value>
      <webElementGuid>fdbd328d-2417-4fe0-8a6a-e0a6690e4299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nee'])[2]/preceding::label[1]</value>
      <webElementGuid>3d9aa0e6-0d26-4fd4-8b14-6a1a62a18a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/label</value>
      <webElementGuid>8a4d0d5a-54d0-4e40-a027-cefdf24f88e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@title = 'Ja' and (text() = ' Ja' or . = ' Ja')]</value>
      <webElementGuid>a593b71d-02f1-46d5-a8c5-7c272479500f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
