<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ja</name>
   <tag></tag>
   <elementGuidId>1134b07e-df99-4699-b4c5-cd99a76dd51b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.label_thumbs_positive > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='thumbs-61017']/fieldset/div/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ab2eecfb-23f4-4e51-acf5-c8a1c1a4a922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Ja</value>
      <webElementGuid>cf62cb46-8d67-45c0-92fc-7f7e22a40138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;thumbs-61017&quot;)/fieldset[1]/div[@class=&quot;button-container thumbs-container&quot;]/div[@class=&quot;thumbs-wrapper button&quot;]/label[@class=&quot;label_thumbs_positive&quot;]/span[1]</value>
      <webElementGuid>276f3630-043c-4d94-ad08-91a20fe99cf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='thumbs-61017']/fieldset/div/div/label/span</value>
      <webElementGuid>6ca1e05c-620f-4ac9-a7c8-23deca910d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vond u deze informatie nuttig?'])[1]/following::span[1]</value>
      <webElementGuid>2316ac22-41d1-4b3f-9bff-e28a508a15d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekening betalen'])[2]/following::span[1]</value>
      <webElementGuid>8e8cafd7-2a2e-403e-9a47-b51062b49dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nee'])[2]/preceding::span[1]</value>
      <webElementGuid>f6a5549f-e27b-41da-90e9-d542555c25da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dat is jammer. Kunt u kort vertellen waarom? Dit helpt ons om onze website te verbeteren.'])[1]/preceding::span[2]</value>
      <webElementGuid>0f26abe0-9cae-4b20-9822-1fe5d66d248f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>0019bb81-04d8-4419-8611-b2b5c1aa8f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Ja' or . = ' Ja')]</value>
      <webElementGuid>dd1183c8-3b35-4e01-9909-ef749b0324e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
