<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DDTSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c8c97ab2-2f2e-4b33-b713-f19916aaca51</testSuiteGuid>
   <testCaseLink>
      <guid>46ce7141-7da8-4e21-bec5-dbe84d0371d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WaternetTesten/LoginFlowRecorderDDT</testCaseId>
      <testDataLink>
         <combinationType>MANY</combinationType>
         <id>cac0619a-6e24-4a3a-8192-1a284ed83c3f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/WaternetNieuw</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e63ebc7-b5cf-416f-b58e-ca45639879db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45177f20-c070-4426-ab0b-8e728cdceb8f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
