<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ja</name>
   <tag></tag>
   <elementGuidId>7ac4b4c7-b0b2-49f1-8c6c-e0ae8bbb9f1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cookiemelding-doorgaan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='cookiemelding-doorgaan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>db2443d1-147d-4626-82b3-bab43ed06cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cookiemelding-doorgaan</value>
      <webElementGuid>234caa26-8c81-4519-bdc7-f095bfa90242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button--no-margin js-cookiebar__accept</value>
      <webElementGuid>6a214b1d-8c8d-4336-8d2c-5c6440c82634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>daa2e940-76b9-48ac-a465-61e7d41f7dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ja</value>
      <webElementGuid>71232084-e6d0-47a8-b429-c3482e284b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cookiemelding-doorgaan&quot;)</value>
      <webElementGuid>7df837e1-1c5e-49e9-b806-6c953497568f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='cookiemelding-doorgaan']</value>
      <webElementGuid>84a7e95e-404f-4d9b-8031-7b3f0f706cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cookiemelding']/div[2]/button</value>
      <webElementGuid>a2122eae-f6d3-431e-ab08-6371c24ee9b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='privacy en cookies'])[1]/following::button[1]</value>
      <webElementGuid>c4d0287b-4280-45a7-90c0-e45b2ef14963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookies'])[1]/following::button[1]</value>
      <webElementGuid>494dc9d7-77b5-4871-a290-f0f123fed0ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nee'])[1]/preceding::button[1]</value>
      <webElementGuid>2f986b68-0396-42a2-adc3-0242ea889efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Direct naar content'])[1]/preceding::button[2]</value>
      <webElementGuid>d28a343b-7f7b-4273-a903-a11c182354c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ja']/parent::*</value>
      <webElementGuid>82c5c8b2-0c81-42cb-b3cc-106cca9f9338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>4222fef9-88fb-479e-b50a-b9b9754a585c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'cookiemelding-doorgaan' and (text() = 'Ja' or . = 'Ja')]</value>
      <webElementGuid>73f5575b-8603-41a9-bc87-98ad556cd991</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
