<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Inloggen voorDrinkwater</name>
   <tag></tag>
   <elementGuidId>6e7b5e31-1567-49ad-88b8-d2a00a383419</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.heading.heading--h2.heading--blue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='content']/div[2]/div/div/div/div/div/div/div/button/div/div/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>67520c76-9a51-4718-a224-8c38cba09ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading heading--h2 heading--blue</value>
      <webElementGuid>fcc5ba8e-f144-40f0-8be5-1e6b8999e53d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inloggen voor Drinkwater</value>
      <webElementGuid>a8e0e8d4-6659-4963-98dc-7c0d388c79ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[2]/div[@class=&quot;mijn-login&quot;]/div[@class=&quot;container&quot;]/div[1]/div[@class=&quot;consumer-content&quot;]/div[@class=&quot;row row--gutter row--items-start&quot;]/div[@class=&quot;col-s-12 col-m-12 col-l-6 col-s-gutter col-m-gutter col-l-gutter consumer-content__block-wrapper d-flex&quot;]/div[@class=&quot;container-block consumer-content__intro container-block--no-margin-bottom login-block&quot;]/button[@class=&quot;login-block__cta&quot;]/div[@class=&quot;login-block__intro&quot;]/div[@class=&quot;row row--gutter&quot;]/div[@class=&quot;col-s-12 col-m-7 col-s-gutter col-m-gutter&quot;]/h2[@class=&quot;heading heading--h2 heading--blue&quot;]</value>
      <webElementGuid>d1fa80c9-c02b-4cf6-8adb-673bf368c485</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content']/div[2]/div/div/div/div/div/div/div/button/div/div/div/h2</value>
      <webElementGuid>b57919d8-f6b0-4868-b1c0-b03ad0aaadb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mijn Waternet'])[3]/following::h2[1]</value>
      <webElementGuid>a86be2d7-100c-4979-867f-261c8005109a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[2]/following::h2[1]</value>
      <webElementGuid>6f80fd03-3070-46ca-9384-227847b81921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bekijk en betaal uw rekeningen voor drinkwater'])[1]/preceding::h2[1]</value>
      <webElementGuid>ec67427d-6813-4e99-a501-9c1f5e673456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>5733da14-209e-4dea-a107-3268f3cd4136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Inloggen voor Drinkwater' or . = 'Inloggen voor Drinkwater')]</value>
      <webElementGuid>78e0998a-5c53-40a8-8938-637656be4d86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
