<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Wachtwoord_password</name>
   <tag></tag>
   <elementGuidId>224fb432-91f6-43a6-a281-801348e74372</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mijn_login-wachtwoord</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mijn_login-wachtwoord']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>def443c6-f267-43d6-9d36-99ff37f4b79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mijn_login-wachtwoord</value>
      <webElementGuid>1020f345-f047-4e78-a5f0-64c7800689eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3f165a98-9e0e-4848-84f1-2daa0e00c369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>67133a66-00ac-4e8a-9c8d-e701a27b07fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>524288</value>
      <webElementGuid>69cd5939-ae31-499c-820e-65fb0cc28705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-block__input</value>
      <webElementGuid>ea8add43-0e5a-4110-9e31-2c58356c30e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mijn_login-wachtwoord&quot;)</value>
      <webElementGuid>9e83ebbd-104a-487f-a8ae-db4198b053ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mijn_login-wachtwoord']</value>
      <webElementGuid>495e2d26-a8ab-456c-9bf2-4d9515d20967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-block-0']/div/div/div/div/form/div[2]/div/input</value>
      <webElementGuid>55709726-4f8e-4508-994a-5ef7a326e57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>0983a559-d779-4773-bb3f-804913c56150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mijn_login-wachtwoord' and @name = 'password' and @type = 'password']</value>
      <webElementGuid>1800db57-5dd6-4463-a3bd-5f950d08a65b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
