<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-mailadres_email</name>
   <tag></tag>
   <elementGuidId>c7101d45-d06e-476d-bfe1-06dfc92dee64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mijn_login-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mijn_login-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0da1457f-9bbb-467a-a966-72b149161ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mijn_login-email</value>
      <webElementGuid>08c76f42-2145-4199-902a-cdf2d38d0926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>3584c51f-fac5-4fce-b8ff-f8eded4a07ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b89f7386-0d13-4762-8485-55425f5014dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>53d08eb8-3e57-4f24-9454-8e008811de70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-block__input</value>
      <webElementGuid>e5eea99a-e938-4305-b142-9b798c56c731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mijn_login-email&quot;)</value>
      <webElementGuid>d1acf659-56fe-4c28-a91a-8dd671de8a93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mijn_login-email']</value>
      <webElementGuid>19105c52-c4a1-4494-a34b-8aa1d0643780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-block-0']/div/div/div/div/form/div/div/input</value>
      <webElementGuid>307a789d-3a99-411c-a536-d95757f90cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>5952db55-d7c7-4fda-a5f3-32074ca17125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mijn_login-email' and @name = 'email' and @type = 'text']</value>
      <webElementGuid>131301f9-088d-4bb6-a5c2-fb6134c372c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
