<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ja</name>
   <tag></tag>
   <elementGuidId>66201f2e-c0f0-44b7-9eb4-f18f75a1eaa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cookiemelding-doorgaan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='cookiemelding-doorgaan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6500f500-3c41-45e5-b01e-e6ccd8896d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cookiemelding-doorgaan</value>
      <webElementGuid>6920e41f-717c-43d0-9759-5b9e49bec9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button--no-margin js-cookiebar__accept</value>
      <webElementGuid>5c1c6f75-58e5-4d81-a599-f60b5cd7e5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0adff706-7b39-49ab-a7a1-d0f700a20e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ja</value>
      <webElementGuid>db672cba-c31c-4876-8734-bc80c29a5a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cookiemelding-doorgaan&quot;)</value>
      <webElementGuid>a3fe3569-4bbf-420c-8231-dac8874e5d96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='cookiemelding-doorgaan']</value>
      <webElementGuid>d256a892-d555-466d-a337-7a8a0972976f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cookiemelding']/div[2]/button</value>
      <webElementGuid>01502bfa-c9a4-4644-bc5b-23a93e218d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='privacy en cookies'])[1]/following::button[1]</value>
      <webElementGuid>797124c2-8131-4a82-8fac-2fefcaf0ad2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookies'])[1]/following::button[1]</value>
      <webElementGuid>05847a05-ca81-4ed0-b473-b4062bb0e5dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nee'])[1]/preceding::button[1]</value>
      <webElementGuid>6df191fa-e3fa-45e5-95bf-02e6909a73c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Direct naar content'])[1]/preceding::button[2]</value>
      <webElementGuid>62472505-c576-4703-bcd0-be2b9dc560be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ja']/parent::*</value>
      <webElementGuid>e6295f08-53fa-4f8d-a0f1-6b67ecb12b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>24c4650b-302d-4e55-be6a-a6fb1a6e591c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'cookiemelding-doorgaan' and (text() = 'Ja' or . = 'Ja')]</value>
      <webElementGuid>d7e64a8b-9b53-4823-87f0-28025f21282d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
