<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Nieuws en artikelen</name>
   <tag></tag>
   <elementGuidId>f4b489bd-c219-458d-b9b5-78e385a8d754</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.heading--tight.heading--h2.heading--bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='content']/div/div[2]/div/section/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>c21d7cdc-ee6d-4fb9-8319-24b7621eb15d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading--tight heading--h2 heading--bold</value>
      <webElementGuid>ce2374b9-9353-4de9-8094-7e5e5ac76f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nieuws en artikelen</value>
      <webElementGuid>84e6e80a-c595-467e-8308-35f8756a1ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;container container--fluid container--flush waternet-layout&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;block topicsblock col-xl-12 col-l-12 col-m-12 col-s-12 StartPage&quot;]/section[@class=&quot;page-section&quot;]/div[@class=&quot;container&quot;]/h3[@class=&quot;heading--tight heading--h2 heading--bold&quot;]</value>
      <webElementGuid>8ec146ae-4971-4442-93d7-69ce03c08354</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content']/div/div[2]/div/section/div/h3</value>
      <webElementGuid>46700ecc-6d6a-44f6-a2cd-2e178e95e243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meer drinkwater nodig: aan deze oplossingen werkt Waternet'])[1]/preceding::h3[1]</value>
      <webElementGuid>577d8268-73ac-4c3b-ad77-99b843f9704c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lees meer'])[1]/preceding::h3[1]</value>
      <webElementGuid>4c51e559-81f8-48e6-b14e-867700bf3e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nieuws en artikelen']/parent::*</value>
      <webElementGuid>fdb769bf-6e6b-419a-903e-85c9de9f67cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/h3</value>
      <webElementGuid>30a82c52-c52f-4287-9323-c23e9644a8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Nieuws en artikelen' or . = 'Nieuws en artikelen')]</value>
      <webElementGuid>8d4c9a8c-3c4a-4572-93ee-4e3afb20cbbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
