<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ja</name>
   <tag></tag>
   <elementGuidId>137ad8cf-f38a-4387-9515-ffae3c5b8db3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cookiemelding-doorgaan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='cookiemelding-doorgaan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>451ee551-bad3-4d5f-83c4-78d67c8333a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cookiemelding-doorgaan</value>
      <webElementGuid>f46a29a6-f7a2-42de-ae18-020d044823ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button--no-margin js-cookiebar__accept</value>
      <webElementGuid>10a776eb-1211-46b7-a47e-77080bebddf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>488da4c3-01ec-481f-9199-c38409136aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ja</value>
      <webElementGuid>f3be8fe6-7ee3-4f1c-a921-09e0366e6546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cookiemelding-doorgaan&quot;)</value>
      <webElementGuid>b680d671-c206-467c-914a-e69e30a6b08f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='cookiemelding-doorgaan']</value>
      <webElementGuid>bcf40e1d-103a-486e-81d6-97a40b853463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cookiemelding']/div[2]/button</value>
      <webElementGuid>92062efa-18bd-4dda-8bc1-02fc88407ea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='privacy en cookies'])[1]/following::button[1]</value>
      <webElementGuid>96bc38e8-e488-4f0b-90a3-568c4e7b19fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookies'])[1]/following::button[1]</value>
      <webElementGuid>2ed27468-71b6-4fa0-bc8a-15a027387d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nee'])[1]/preceding::button[1]</value>
      <webElementGuid>4285ce40-7c25-4654-b593-f98831347a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Direct naar content'])[1]/preceding::button[2]</value>
      <webElementGuid>67832927-e4b0-4fb5-8949-b27b3e0000fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ja']/parent::*</value>
      <webElementGuid>bee9b150-1975-4432-9f5b-00d4844e80ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>0dcaa2ed-9c68-47f4-abfb-56178c941bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'cookiemelding-doorgaan' and (text() = 'Ja' or . = 'Ja')]</value>
      <webElementGuid>f63fb55e-4085-48bd-b13d-75d8403c7b67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
