<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verplicht___field_11966</name>
   <tag></tag>
   <elementGuidId>2be7d150-dc71-4a21-ae8e-e3235f9945d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a4956699-eb06-4a4d-a311-d5cd37f1a807</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='a4956699-eb06-4a4d-a311-d5cd37f1a807']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee0ebe94-7db9-49f9-94bb-9abfbc187095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a4956699-eb06-4a4d-a311-d5cd37f1a807</value>
      <webElementGuid>2d493a85-b59b-48a6-93b0-fbb92ffb66cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__field_11966</value>
      <webElementGuid>1d1bb710-ab4f-4e14-8e5d-b44dc31271ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6fedaed7-ba15-4b66-ba5f-6cb4ab541b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FormTextbox__Input</value>
      <webElementGuid>8376cfc8-fdc8-4c97-ad33-2ae2fbae70c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d6187d1c-3dc8-48a4-8b7a-e7267acdf687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a4956699-eb06-4a4d-a311-d5cd37f1a807&quot;)</value>
      <webElementGuid>81344b0e-10e5-4b20-b8cb-263786184bd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='a4956699-eb06-4a4d-a311-d5cd37f1a807']</value>
      <webElementGuid>c5e444e6-dd8f-468b-84ce-efc295991516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='__field_']/div[2]/div[2]/input</value>
      <webElementGuid>3b966636-73c8-472f-9518-566c109ece9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>ed2c9f57-dfbd-4da2-900a-64663292a4f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'a4956699-eb06-4a4d-a311-d5cd37f1a807' and @name = '__field_11966' and @type = 'text']</value>
      <webElementGuid>cb660625-8869-4ee4-b0da-7c6b84eece16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
