<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_i___field_11967</name>
   <tag></tag>
   <elementGuidId>ddcaf8c2-5215-44a0-bebc-868b970af05a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#6c0b6af9-0a17-4d0c-978c-4ed95abfc45c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='6c0b6af9-0a17-4d0c-978c-4ed95abfc45c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>755f73fd-30af-459a-911f-edf8260266eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>6c0b6af9-0a17-4d0c-978c-4ed95abfc45c</value>
      <webElementGuid>ff7c8832-2976-42f9-b076-357588a2508d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__field_11967</value>
      <webElementGuid>246642ef-a19e-4d0d-9002-629aba27577c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ebd9b050-1831-45f4-ac66-51286a0ae2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FormTextbox__Input</value>
      <webElementGuid>d0e2d5ed-461a-4eee-8d78-27ed98a65f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>We gebruiken uw e-mailadres alleen om op uw compliment of tip te reageren.</value>
      <webElementGuid>c99933e8-f73a-466f-a0ed-67bb638165b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e74422a6-1ae5-4f76-a5df-16721fec7bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6c0b6af9-0a17-4d0c-978c-4ed95abfc45c&quot;)</value>
      <webElementGuid>893da41f-9548-45cd-967a-6fe102116817</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='6c0b6af9-0a17-4d0c-978c-4ed95abfc45c']</value>
      <webElementGuid>ba054f28-21de-42b5-999f-0729cdb8b748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='__field_']/div[3]/div[2]/input</value>
      <webElementGuid>6c9290b8-3fb3-41a5-b7f6-3c970bba7fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>29b62d8e-e304-4bec-8928-a0d43f1aedd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '6c0b6af9-0a17-4d0c-978c-4ed95abfc45c' and @name = '__field_11967' and @type = 'text' and @title = 'We gebruiken uw e-mailadres alleen om op uw compliment of tip te reageren.']</value>
      <webElementGuid>c34aedec-f570-42e5-a5d4-ca9c8481acd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
