<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verplicht___field_11965</name>
   <tag></tag>
   <elementGuidId>cbfb767e-ea8e-4590-89d3-09d1f19dfbe6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#057b513b-d6af-4fcd-ba67-c38d198d443a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='057b513b-d6af-4fcd-ba67-c38d198d443a']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b2827a2-ecc4-4239-94df-44be0088b519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>057b513b-d6af-4fcd-ba67-c38d198d443a</value>
      <webElementGuid>c325d166-f373-44d8-a03b-3d8002e57243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__field_11965</value>
      <webElementGuid>2976c7e7-eb18-48b9-9252-94d337252ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>530312c5-763c-4ea0-887f-4ddcdcbcb6e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FormTextbox__Input</value>
      <webElementGuid>1b90b97e-7ec5-47bd-8faf-b6a46fe988fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5e933bf3-2a3c-4860-b7c8-02d307fe541d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;057b513b-d6af-4fcd-ba67-c38d198d443a&quot;)</value>
      <webElementGuid>510f4649-ca75-47af-b040-30220ace036a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='057b513b-d6af-4fcd-ba67-c38d198d443a']</value>
      <webElementGuid>3d093256-faa0-483e-8728-ad3be6dc2b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='__field_']/div/div[2]/input</value>
      <webElementGuid>ad8505ce-0ef4-4623-b38a-c308f52c08a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>85ed4804-aec4-44cc-91cf-10408f87caa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '057b513b-d6af-4fcd-ba67-c38d198d443a' and @name = '__field_11965' and @type = 'text']</value>
      <webElementGuid>1392c290-1d53-4c02-8666-c09ed6d1ff90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
