<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Verplicht___field_11969</name>
   <tag></tag>
   <elementGuidId>74c66c25-9ea4-41c6-aeb9-66a36ffbf694</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e090a9ed-b05f-46c7-aaad-47225dd67127</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='e090a9ed-b05f-46c7-aaad-47225dd67127']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c5e19701-1afe-473e-912f-b9207d224b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__field_11969</value>
      <webElementGuid>19a89505-b0b1-49d5-8444-25780c40bc8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e090a9ed-b05f-46c7-aaad-47225dd67127</value>
      <webElementGuid>9dd4c59a-3e6f-4c61-8898-ffbd75ef1679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FormTextbox__Input</value>
      <webElementGuid>7fe0aa86-af0a-4e30-9269-ce75099fa231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-epiforms-label</name>
      <type>Main</type>
      <value>Uw opmerking of tip</value>
      <webElementGuid>33fe1d91-3ef8-4acb-8033-c0c21ef6dfef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2a12fad0-e736-4868-9974-0e97135e74f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e090a9ed-b05f-46c7-aaad-47225dd67127&quot;)</value>
      <webElementGuid>87662785-2a4f-4be8-9f62-913190b8659e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='e090a9ed-b05f-46c7-aaad-47225dd67127']</value>
      <webElementGuid>eeeaae90-ecc2-4e86-8c34-304cdda3fce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='__field_']/div[4]/div[2]/textarea</value>
      <webElementGuid>b4aaa847-23a0-4499-acb5-3cbe74c898c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>f9c867b3-5108-4969-93e3-3d0c2c387322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = '__field_11969' and @id = 'e090a9ed-b05f-46c7-aaad-47225dd67127']</value>
      <webElementGuid>b65d9d54-4691-4e05-83f2-53546475f18e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
